### ISSUE TITLE
The splat workaround no longer works with latest terraform

### ISSUE THREAD

**Issue by polewskm** [hashicorp/terraform-aws-consul-ecs#123]
- Terraform version: 1.2.3
- Mesh module version: 0.4.1

https://github.com/hashicorp/terraform-aws-consul-ecs/blob/v0.4.1/modules/mesh-task/iam.tf#L2

The workaround still produces the following error:
```
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be
│ created. To work around this, use the -target argument to first apply only
│ the resources that the count depends on.
```

I also tried specifying `depends_on` so that the IAM roles are created before the mesh module and that didn't work either.

**Comment by polewskm** [comment]
Since that requires Consul 1.12.0+ which is out of my control to upgrade, what are my options?

**Comment by pglass** [comment]
Can you explain how you are using the module? Are you passing in IAM roles (using `task_role` or `execution_role`)?  Or are you experiencing this issue without passing in any IAM roles?

**Comment by polewskm** [comment]
Yes, I am passing in IAM roles that I am creating. Here is a snippet:
```
  task_role = {
    id  = aws_iam_role.api.id
    arn = aws_iam_role.api.arn
  }

  execution_role = {
    id  = aws_iam_role.ecs.id
    arn = aws_iam_role.ecs.arn
  }

  consul_client_token_secret_arn = /* REDACTED */
  acl_secret_name_prefix         = /* REDACTED */

```

I see that v0.5.0 has a new variable for `create_task_role` which probably will fix my problem. But doesn't that version also require Consul 1.12.0+? My infrastructure/environment is still using Consul v1.8.13 which is out of my control to upgrade.

From reading the change log, it looks like v0.5.0 was updated to use Consul AWS IAM auth and removed the `consul_client_token_secret_arn` and `acl_secret_name_prefix ` variables which I presume I must still use because I am not on Consul 1.12.0+.

**Comment by pglass** [comment]
Hi @polewskm, thanks for your patience.

We are planning on releasing a 0.4.2 version of the Terraform modules to fix this for you.

Since this only requires changing the Terraform modules, we will not a release a new version of the `consul-ecs` Docker image for the time being. When using version 0.4.2 of mesh-task, you will see your ECS tasks running the `hashicorp/consul-ecs:0.4.1` image.

Separately, I want to let you know that [Consul 1.8 is no longer maintained](https://discuss.hashicorp.com/t/question-about-supported-consul-versions/33222), so we do encourage your organization to upgrade to a newer version when possible.

**Comment by pglass** [comment]
Hi @polewskm, 

We've released [v0.4.2](https://registry.terraform.io/modules/hashicorp/consul-ecs/aws/0.4.2/submodules/mesh-task?tab=inputs) which should fix this issue. Let us know if you have any issues.

In 0.4.2, mesh-task will no longer attach any policies to the roles you pass in, so when secure feature are enabled, you must configure the execution role yourself with permission to fetch the secrets.

To use 0.4.2, make sure to do the following:

1. Pass `create_task_role = false` and `create_execution_role = false`
2. If secure features are enabled (TLS, gossip encryption, ACLs), then you must create a policy for the execution role that gives permission to inject the necessary secrets into the task. There is a new output variable `service_token_secret_arn`, which the execution role must have permission to retrieve. See the following example (and excuse any syntax errors I might have):

```terraform
module "test_server" {
  source  = "hashicorp/consul-ecs/aws"
  version = "0.4.2"
  ...

  tls                            = true
  acls                           = true
  consul_server_ca_cert_arn      = "<server-ca-cert-secret-arn>"
  gossip_key_secret_arn          = "<gossip-key-secret-arn>"
  consul_client_token_secret_arn = "<client-token-secret-arn>"

  create_task_role      = false
  create_execution_role = false
  task_role             = aws_iam_role.task
  execution_role        = aws_iam_role.execution
}

// Create the policy with the ability to access secrets
// Be sure to include the service_token_secret_arn from the mesh-task outputs.
resource "aws_iam_policy" "exec-role-policy" {
  name   = "my-exec-role-policy"
  path   = "/"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "secretsmanager:GetSecretValue"
      ],
      "Resource": [
        "<server-ca-cert-secret-arn>",
        "<gossip-key-secret-arn>",
        "<client-token-secret-arn>",
        "${module.test_server.service_token_secret_arn}"
      ]
    }
  ]
}
EOF

// Attach the policy to the execution role.
resource "aws_iam_role_policy_attachment" "exec-role-policy-attach" {
  role       = aws_iam_role.execution.id
  policy_arn = aws_iam_policy.exec-role-policy.arn
}

```

**Comment by pglass** [comment]
Closing this issue for now! Let us know if you encounter any problems.

**Comment by polewskm** [comment]
Awesome! Thank you everyone for the super quick turnaround.
