### ISSUE TITLE
consul_https_ca_cert_arn using ACM

### ISSUE THREAD

**Issue by polewskm** [hashicorp/terraform-aws-consul-ecs#155]
How are we supposed to specify `consul_https_ca_cert_arn` when Consul's certificate is from ACM? In that use-case, we don't have access  to the CA.

**Comment by polewskm** [comment]
I figured it out.

For any traffic going through our ALB, I added the [AWS root CAs](https://docs.aws.amazon.com/acm/latest/userguide/acm-concepts.html#ACM-root-CAs).

Then I concatenated our private CA.

Luckily both the acl-controller and mesh-task allow a CA file with multiple certificates.

**Comment by cthain** [comment]
Thanks for the issue @polewskm. I'm glad to hear that you got it resolved!

Thanks for posting your solution, it may be helpful for others with the same use case.
