### ISSUE TITLE
Is variable outbound_only really needed?

### ISSUE THREAD

**Issue by v-rosa** [hashicorp/terraform-aws-consul-ecs#196]
Seems that variable `outbound_only` is used only to do some kind of asserts here : https://github.com/hashicorp/terraform-aws-consul-ecs/blob/39ddfcb89da7d4eda4ffcfaef7d7d099b20d4a6f/modules/mesh-task/validation.tf#L5

I'm trying to understand if this affects the consul side cars bootstrap in any way.

Am I missing something?

**Comment by Ganeshrockz** [comment]
👋 @v-rosa This does not affect the sidecar bootstrap in any way. This variable was just added to make sure users are aware of setting the port as `0` (when they forget to do so) because most services accept incoming traffic. I hope this answers your query.
