### ISSUE TITLE
Security group is missing for acl-controller

### ISSUE THREAD

**Issue by polewskm** [hashicorp/terraform-aws-consul-ecs#88]
The `acl-controller` submodule creates an ECS service without specifying a security group ([reference](https://github.com/hashicorp/terraform-aws-consul-ecs/blob/077459f554c8b391c440f4d01c9264a134c7c0d5/modules/acl-controller/main.tf)).

This results in the default security group for the VPC being used and if no inbound or outbound rules are defined, then the ECS service fails to start. AWS also seems to say that the security group is a required argument in the ECS dashboard.

This was verified by creating the `acl-controller` ECS service manually in the AWS console and specify a security group that does contains inbound and outbound rules.

**Comment by pglass** [comment]
Hi, this is fixed in main. It should released as part of 0.4.0 next week.
